-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-12-22 16:13:11 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE concerte (
    id_concert   NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nume_concert VARCHAR2(40) NOT NULL,
    data         DATE NOT NULL,
    oras         VARCHAR2(30) NOT NULL,
    id_dirijor   NUMBER(2) NOT NULL
)
LOGGING;

ALTER TABLE concerte
    ADD CONSTRAINT concert_nume_concert_ck CHECK ( length(nume_concert) > 1 );

ALTER TABLE concerte
    ADD CONSTRAINT concerte_oras_ck CHECK ( length(oras) > 1 );

CREATE UNIQUE INDEX concerte__idx ON
    concerte (
        id_dirijor
    ASC )
        LOGGING;

ALTER TABLE concerte ADD CONSTRAINT concerte_pk PRIMARY KEY ( id_concert );

ALTER TABLE concerte ADD CONSTRAINT concerte_nume_concert_un UNIQUE ( nume_concert );

CREATE TABLE dirijori (
    id_dirijor    NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nume          VARCHAR2(30) NOT NULL,
    email         VARCHAR2(30),
    nr_de_telefon VARCHAR2(20)
)
LOGGING;

ALTER TABLE dirijori
    ADD CONSTRAINT dirijori_nume_ck CHECK ( length(nume) > 1 );

ALTER TABLE dirijori
    ADD CONSTRAINT dirijori_adresa_ck CHECK ( REGEXP_LIKE ( email,
                                                            '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE dirijori ADD CONSTRAINT dirijori_pk PRIMARY KEY ( id_dirijor );

ALTER TABLE dirijori ADD CONSTRAINT dirijori_nume_uk UNIQUE ( nume );

CREATE TABLE instrumente (
    id_instrument NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nume          VARCHAR2(30) NOT NULL,
    categorie     VARCHAR2(20) NOT NULL
)
LOGGING;

ALTER TABLE instrumente
    ADD CONSTRAINT instrumente_nume_ck CHECK ( length(nume) > 1 );

ALTER TABLE instrumente
    ADD CONSTRAINT instrumente_categorie_ck CHECK ( categorie IN ( 'coarda_arcus', 'complexe', 'percutie', 'suflat' ) );

ALTER TABLE instrumente ADD CONSTRAINT instrumente_pk PRIMARY KEY ( id_instrument );

CREATE TABLE muzicieni (
    id_muzician   NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nume          VARCHAR2(30) NOT NULL,
    nr_de_telefon VARCHAR2(20),
    email         VARCHAR2(30),
    id_instrument NUMBER(2) NOT NULL
)
LOGGING;

ALTER TABLE muzicieni
    ADD CONSTRAINT muzicieni_nume_ck CHECK ( length(nume) > 1 );

ALTER TABLE muzicieni
    ADD CONSTRAINT muzicieni_adresa_ck CHECK ( REGEXP_LIKE ( email,
                                                             '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE muzicieni ADD CONSTRAINT muzicieni_pk PRIMARY KEY ( id_muzician );

ALTER TABLE muzicieni ADD CONSTRAINT muzicieni_nume_uk UNIQUE ( nume );

CREATE TABLE participari (
    id_muzician NUMBER(2) NOT NULL,
    id_concert  NUMBER(2) NOT NULL,
    loc_scena   NUMBER(2)
)
LOGGING;

ALTER TABLE participari ADD CONSTRAINT id_participare PRIMARY KEY ( id_muzician,
                                                                    id_concert );

CREATE TABLE piese (
    id_piesa         NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    titlu_piesa      VARCHAR2(30) NOT NULL,
    numele_autorului VARCHAR2(30)
)
LOGGING;

ALTER TABLE piese
    ADD CONSTRAINT piese_titlu_piesa_ck CHECK ( length(titlu_piesa) > 1 );

ALTER TABLE piese
    ADD CONSTRAINT piese_numele_autorului_ck CHECK ( length(numele_autorului) > 1 );

ALTER TABLE piese ADD CONSTRAINT piese_pk PRIMARY KEY ( id_piesa );

ALTER TABLE piese ADD CONSTRAINT piese_titlu_piesa_un UNIQUE ( titlu_piesa );

CREATE TABLE repertoriu (
    id_concert          NUMBER(2) NOT NULL,
    id_piesa            NUMBER(2) NOT NULL,
    ordine_interpretare NUMBER(2) NOT NULL
)
LOGGING;

ALTER TABLE repertoriu ADD CONSTRAINT id_repertoriu PRIMARY KEY ( id_concert,
                                                                  id_piesa );

ALTER TABLE participari
    ADD CONSTRAINT concerte_participari_fk FOREIGN KEY ( id_concert )
        REFERENCES concerte ( id_concert )
    NOT DEFERRABLE;

ALTER TABLE repertoriu
    ADD CONSTRAINT concerte_repertoriu_fk FOREIGN KEY ( id_concert )
        REFERENCES concerte ( id_concert )
    NOT DEFERRABLE;

ALTER TABLE concerte
    ADD CONSTRAINT dirijori_concerte_fk FOREIGN KEY ( id_dirijor )
        REFERENCES dirijori ( id_dirijor )
    NOT DEFERRABLE;

ALTER TABLE muzicieni
    ADD CONSTRAINT instrumente_muzicieni_fk FOREIGN KEY ( id_instrument )
        REFERENCES instrumente ( id_instrument )
    NOT DEFERRABLE;

ALTER TABLE participari
    ADD CONSTRAINT muzicieni_participari_fk FOREIGN KEY ( id_muzician )
        REFERENCES muzicieni ( id_muzician )
    NOT DEFERRABLE;

ALTER TABLE repertoriu
    ADD CONSTRAINT piese_repertoriu_fk FOREIGN KEY ( id_piesa )
        REFERENCES piese ( id_piesa )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
